name: Build and Push Docker Image to Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Logga in på Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bygg och pusha Docker-image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:1.0 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:1.0
